language: cpp
dist: xenial
compiler:
  - gcc
  # - clang 

addons: 
  apt: 
    packages: libboost-all-dev

install: 
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint.sh

services:
 - xvfb

script: 
  - ./download_other_githubs.sh
  - ./build_other_githubs.sh
  - qmake -qt=qt5 StyleSheetSetterDesktop.pro
  - make --silent
  - ./StyleSheetSetterDesktop &
  - sudo killall -9 StyleSheetSetterDesktop
  # cppcheck
  - cppcheck --quiet --error-exitcode=1 . 
  # Get code coverage
  - ./get_code_cov.sh >/dev/null
  - codecov
  # Call OCLint
  - ./do_oclint.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
